name: news_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_native_splash: ^2.1.6
  path: ^1.8.1
  carousel_slider: ^4.1.1
  bloc: ^8.0.3
  flutter_bloc: ^8.0.1
  dio: ^4.0.6
  rxdart: ^0.27.3
  url_launcher: ^6.1.2
  timeago: ^3.2.2
  flutter_html: ^2.2.1

dev_dependencies:

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
flutter_native_splash:
  image: "assets/logo.png"
  color: "#191826"
  android: false
  web: false